# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  forest_env_secret: a7309f7da8ffceaf56b8b69f7b90b54eb635bee4a531956f4b44dd05c38180c3
  forest_auth_secret: YkMtfkgHb86R3RJHvPNx1Q
  secret_key_base: bd3fc460804f9fcf72031321c66a1ca87e34ea9ca4082db8921417a9c93a3d692416cdf27f79f0d4e6a5e039b548f7b1e964acb20dc914dea5a8385a2b1e6ff2


test:
  secret_key_base: fccd5d9a957ba455784930407a4aaf7ba37a1dccae876b443aefd3003c648d9c83bed8f2b25d0d656d135122fe181c6a71c01677c473a7a355710c6b9a9875e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
  production:
    forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
    forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
